# Generated by Django 5.0.7 on 2024-07-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_development_link_development_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="skills/"),
        ),
    ]
