# Generated by Django 5.0.7 on 2024-07-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_skill_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="progress",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
