# Generated by Django 5.0.7 on 2024-07-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_skill_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="development",
            name="image_mime_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="image_mime_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="development",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
